export type WordPair = {
  common: string;
  undercover: string;
};

const WORD_POOL: WordPair[] = [
  { common: "กาแฟ", undercover: "ชา" },
  { common: "วัดเส้าหลิน", undercover: "นักเตะเสี้ยวลิ้มยี่" },
  { common: "แมว", undercover: "เสือ" },
  { common: "ฟ้าร้อง", undercover: "ฟ้าแลบ" },
  { common: "กีต้าร์", undercover: "ไวโอลิน" },
  { common: "อ่างอาบน้ำ", undercover: "ฝักบัว" },
  { common: "สิงค์โปร", undercover: "ฮ่องกง" },
  { common: "หัวหอม", undercover: "กระเทียม" },
  { common: "อ่างจากุชชี่", undercover: "อาบอบนวด" },
  { common: "ไวรัส", undercover: "แบคทีเรีย" },
  { common: "เมฆ", undercover: "หมอก" },
  { common: "Ironman", undercover: "Superman" },
  { common: "ฮอบบิท", undercover: "ลอร์ดออฟเดอะริง" },
  { common: "Netflix", undercover: "Youtube" },
  { common: "Coke", undercover: "Pepsi" },
  { common: "หนองน้ำ", undercover: "ป่า" },
  { common: "ผีเสื้อ", undercover: "นก" },
  { common: "ลูกอม", undercover: "หมากฝรั่ง" },
  { common: "จูบ", undercover: "กอด" },
  { common: "ไอศครีม", undercover: "โยเกิร์ต" },
  { common: "สวนสัตว์", undercover: "พิพิธภัณฑ์สัตว์น้ำ" },
  { common: "เชอร์รี่", undercover: "สตรอเบอร์รี่" },
  { common: "ค้อน", undercover: "ตะปู" },
  { common: "วาฬ", undercover: "โลมา" },
  { common: "ลิฟต์", undercover: "บรรไดเลื่อน" },
  { common: "เครื่องบิน", undercover: "จรวด" },
  { common: "วันแดงเดือด", undercover: "ลิเวอร์พูล" },
  { common: "มัดย้อม", undercover: "ยืดเปล่า" },
  { common: "หมอผี", undercover: "หมอดู" },
  { common: "แฮม", undercover: "เบค่อน" },
  { common: "พิมพ์ดีด", undercover: "คีย์บอร์ด" },
  { common: "บันจี้จัมป์", undercover: "กระโดดร่ม" },
  { common: "เมสเซนเตอร์", undercover: "ไรเดอร์" },
  { common: "ซาลาเปา", undercover: "หมั่นโถว" },
  { common: "ท้องเสีย", undercover: "ท้องผูก" },
  { common: "นางตะเคียน", undercover: "นางตานี" },
  { common: "ลูฟี่", undercover: "แจ็กสแปร์โรว์" },
  { common: "อินเทอร์เน็ตไร้สาย", undercover: "บลูทูธ" },
  { common: "ผ้าพันคอ", undercover: "ผ้าคลุมไหล่" },
  { common: "กามเทพ", undercover: "แม่สื่อ" },
  { common: "หมวกกันน็อค", undercover: "หมวกนิรภัย" },
  { common: "คอนโด", undercover: "อะพาร์ตเมนต์" },
  { common: "ยมทูต", undercover: "ยมบาล" },
  { common: "ผีสิง", undercover: "ร่างทรง" },
  { common: "โซฟาทะเล", undercover: "บานาน่าโบ้ท" },
  { common: "รถสองแถว", undercover: "รถเมล์" },
  { common: "โอเลี้ยง", undercover: "อเมริกาโน่" },
  { common: "Universal", undercover: "Disneyland" },
  { common: "ฟองน้ำล้างจาน", undercover: "ฝอยขัดหม้อ" },
  { common: "JamesBond007", undercover: "Mission Impossible" },
  { common: "ข้าวต้มมัด", undercover: "ข้าวหลาม" },
  { common: "หัวแถว", undercover: "นายหน้า" },
  { common: "ซีอิ๊ว", undercover: "น้ำปลา" },
  { common: "ชักว่าว", undercover: "ชักเย่อ" },
  { common: "กล้องฟิล์ม", undercover: "กล้องดิจิตอล"},
  { common: "สเลท", undercover: "รีพอร์ต"},
  { common: "เพื่อนสนิท", undercover: "คู่รัก"},
  { common: "พริกน้ำปลา", undercover: "น้ำพริก"},
  { common: "ปลาฉลาม", undercover: "แมงกะพรุน"},
  { common: "พายุหิมะ", undercover: "หิมะถล่ม"},
  { common: "พิคาชู", undercover: "กระรอกแมว"},
  { common: "กางเกงใน", undercover: "ชุดชั้นใน"},
  { common: "เบนซิน", undercover: "ดีเซล"},
];

export function pickWordPair(): WordPair {
  const idx = Math.floor(Math.random() * WORD_POOL.length);
  return WORD_POOL[idx];
}
